import React from 'react';
import type { Metadata } from 'next'
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

interface BaseLayoutProps {
    showHeader?: boolean;
    showFooter?: boolean;
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const Header = dynamic(() => import('@/components/partials/Header'));
const Footer = dynamic(() => import('@/components/partials/Footer'));

export default function RootLayout({
    children,
    showFooter = true,
    showHeader = true
}: BaseLayoutProps) {
    return (
        <React.Fragment>
            <html lang="en">
                <body className={inter.className}>

                    {showHeader && <Header />}
                    {/* <SeachModal /> */}
                    <main className='text-white'>
                        {children}
                    </main>
                    {showFooter && <Footer />}



                </body>
            </html>
        </React.Fragment>
    )
}
